### ISSUE TITLE
Página P&D&I não está carregando os dados

### ISSUE THREAD

**Issue by paulormm** [hub-usp-inovacao/platform#125]
De acordo com o Alfredo, a Página P&D&I é a mais importante no momento:
https://hubusp.inovacao.usp.br/inovacao
- [x]  mensagem para o usuário
- [x] Verificar o que deixou de funcionar
- [x] Avaliar solução para mitigar este tipo de problema no longo prazo, ou seja, para não ficarmos dependentes de coisas de terceiros (se é que isso é possível) que podem deixar de ser acessível
- [ ] Inclusão de keywords no catálogo
- [ ] Teste (ver com o @jooaodanieel )

**Comment by paulormm** [comment]
Repetida com a #117

**Comment by luizcarlosdk** [comment]
Está issue está quase pronta, porém falta uma correção na parte de mostrar as 'tags' do PDI

**Comment by luizcarlosdk** [comment]
A solução da issue está atualmente assim:

![image](https://github.com/hub-usp-inovacao/platform/assets/61715930/abed956c-1650-4102-8174-3970d167b217)

**Comment by paulormm** [comment]
> A solução da issue está atualmente assim:
> 
> ![image](https://user-images.githubusercontent.com/61715930/239597732-abed956c-1650-4102-8174-3970d167b217.png)

@neylorfabiano e @hubuspinovacao vocês pode verificar a solução atual aqui mostrada pelo Luiz. A ideia é subir dessa forma enquanto a equipe investiga a questão das tags.
