### ISSUE TITLE
Guardar quantidade de sócios total (com ou sem vínculo com a usp)

### ISSUE THREAD

**Issue by mariliatd** [hub-usp-inovacao/platform#146]

**Comment by josemayer** [comment]
Aguardando a confirmação de como os dados serão tratados na planilha.

**Comment by paulormm** [comment]
> 
Por favor, @neylorfabiano ou @hubuspinovacao confirme se é isso mesmo ^

**Comment by hubuspinovacao** [comment]
Ciente

**Comment by neylorfabiano** [comment]
é isso ai!

**Comment by josemayer** [comment]
- Enviar, na planilha de atualização, a quantidade absoluta de sócios cadastrados.
