### ISSUE TITLE
Validação de Email invalida emails personalizados

### ISSUE THREAD

**Issue by luizcarlosdk** [hub-usp-inovacao/platform#167]
No caso de um email no estilo nome@empresa.org.br, a validação falha pelo fato de não terminar com .com

**Comment by josemayer** [comment]
A validação dos e-mails não está falhando por enquanto. O responsável por essa validação é uma expressão regular do módulo URI, como observado em `backend/app/models/company_update.rb`:

<img width="434" src="https://github.com/hub-usp-inovacao/platform/assets/75316256/5df60b7a-9356-4260-a8b0-a56df0b171de">
