### ISSUE TITLE
Campo natureza da empresa: dois campos separados - código e texto - classificação de atividade econômica

### ISSUE THREAD

**Issue by clarayuki** [hub-usp-inovacao/platform#173]
o formato do código será separado na parte numérica e na parte descritiva. A busca do empreendedor poderá ser feita através dos dois campos. A medida que o empreendedor preencher o número ou escrever alguma palavra-chave no campo, as opções irão aparecer para que o mesmo possa escolher.

**Comment by josemayer** [comment]
- Digitar o código ou parte da descrição de natureza jurídica e mostrar recomendações de seleção prévias de acordo com a lista definida em https://concla.ibge.gov.br/images/concla/documentacao/CONCLA-TNJ2021-EstruturaDetalhada.pdf.
