### ISSUE TITLE
Alterar "CIETEC" por "Incubadora USP/IPEN"

### ISSUE THREAD

**Issue by paulormm** [hub-usp-inovacao/platform#175]
- [x] Verificar se precisa alterar no "código" para o site receber essa informação (Lara irá alterar nas planilhas)
- [x] Alterar em "iniciativas" (somente na planilha)
- [x] Alterar no formulário de atualização
- [x] Alterar em "empresas" (somente na planilha)

**Comment by clarayuki** [comment]
- Alteramos os textos de "CIETEC" para "Incubadora USP/IPEN" apenas no formulário de atualização. 
- Em "iniciativas", não precisamos alterar nada do código (basta atualizar na planilha de iniciativas). 
- Em "empresas", também não alteramos o código. Acreditamos que quando forem alterados os dados da planilha, o filtro será atualizado, mas ainda faremos uma nova verificação quando a planilha for atualizada.

**Comment by hubuspinovacao** [comment]
Prezados, bom dia!

Alterações realizadas.

Atenciosamente,
Lara Guimarães

Hub USPInovação | Agência USP de Inovação
***@***.***
hubusp.inovacao.usp.br


Em sex., 26 de mai. de 2023 às 15:55, Clara Yuki Sano <
***@***.***> escreveu:
