### ISSUE TITLE
Adicionar mensagem de erro quando a logo já existe, mas não é preenchida

### ISSUE THREAD

**Issue by clarayuki** [hub-usp-inovacao/platform#193]
Quando a logo já existe, é mostrada uma mensagem de warning acima de seu campo que indica que a empresa precisa fazer um novo upload. Porém, caso a pessoa não passe por essa aba e vá direto para o encerramento, ocorre um erro de envio do formulário que não especifica em qual aba ou campo está o erro.

**Comment by josemayer** [comment]
A issue já foi resolvida com o alerta de warning. Não conseguimos reproduzir novamente o erro reportado.
