### ISSUE TITLE
Possibilidade de fazer upload do logo da empresa

### ISSUE THREAD

**Issue by luizcarlosdk** [hub-usp-inovacao/platform#99]

**Comment by luizcarlosdk** [comment]
Coluna Q (Logotipo da empresa): Em branco. Verificar a possibilidade do link vir junto na planilha de atualizações.

**Comment by josemayer** [comment]
- Enviar logo mesmo se a empresa não a atualizou (apenas mandar em branco quando a empresa resolver retirá-la)
- Deixar mensagem de logo não carregada mais clara, a fim de que empresas que já possuem logo enviem novamente para registrá-la no servidor interno.

**Comment by paulormm** [comment]
> * Enviar logo mesmo se a empresa não a atualizou (apenas mandar em branco quando a empresa resolver retirá-la)
> 
>     * Deixar mensagem de logo não carregada mais clara, a fim de que empresas que já possuem logo enviem novamente para registrá-la no servidor interno.

lembrar de ajustar a mensagem de alerta quando a imagem não for carregada.
